#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL 16
#undef DEBOUNCE
#define DEBOUNCE 3
#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED 10
#undef MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX 30
